In [138]:
# Necessary import statements:
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import numpy as np
from numpy import random
from sklearn.linear_model import LogisticRegression
from scipy.stats import sem

In [139]:
# read default excel sheet:
df = pd.read_excel('Default.xlsx')

# output dataset to make sure it is well read:
df.head(3)

Unnamed: 0 default student      balance        income
0           1      No      No   729.526495  44361.625074
1           2      No     Yes   817.180407  12106.134700
2           3      No      No  1073.549164  31767.138947

# Part A: 
Perform Multiple Logistic Regression (balance and income) and determine coefficients associated with income and balance

In [140]:
# code provided by Dr. Medina:
formula = 'default ~ income + balance'
sm_model = smf.glm(formula, data=df, family=sm.families.Binomial()).fit()
print(sm_model.summary() )

print("income coef:", sm_model.params[1] )
print("balance coef:", sm_model.params[2] )

                        Generalized Linear Model Regression Results                        
Dep. Variable:     ['default[No]', 'default[Yes]']   No. Observations:                10000
Model:                                         GLM   Df Residuals:                     9997
Model Family:                             Binomial   Df Model:                            2
Link Function:                               logit   Scale:                          1.0000
Method:                                       IRLS   Log-Likelihood:                -789.48
Date:                             Wed, 05 May 2021   Deviance:                       1579.0
Time:                                     04:07:27   Pearson chi2:                 6.95e+03
No. Iterations:                                  9                                         
Covariance Type:                         nonrobust                                         
                 coef    std err          z      P>|z|      [0.025      0.975]
-

The estimated standard error for the coefficient associated with income is 4.99e-06.
The estimated standard error for the coefficient associated with balance is 0.

# Part B: 
Write a function that takes as input the Default data set as well as an index of the observations, and that outputs the coefficient estimates for income and balance in the multiple logistic regression mode

In [141]:
# part B:
def partB(default, indicies):
  # create a new data set using the indices provided:
  data = default.values
  bootstraped_elems = []
  for i in range(len(data)):
    bootstraped_elems.append(data[indicies[i]])
  arr = np.array(bootstraped_elems)

  # find the coefficients of the data:
  clf = LogisticRegression(random_state=0).fit(arr[:, 3:], arr[:, 1])
  return clf.coef_[0]

# Part C:
Use the random.choice function to perform bootstrapping together with the function you created in (b) to estimate the standard errors of the logistic regression coefficient for income and balance.

In [142]:
# store the seperate coefficients here:
coefficients = []

In [143]:
# I will bootstrap 100 times:
for i in range(100):
  # I will use random.choice to bootstrap the indices that I will use. 
  # However the requirements doc indicates to enter the default set and indices into the function form part b, 
  # so I will boot strap the actual elements using the indices I "bootstrap" here:
  size_of_df = len(df.values)
  indices = [i for i in range(size_of_df)]
  bootstrapped_indices = []
  # it must be in range of size of df b/c it the bootstrap must be the same size as original dataset according to lecture.
  for i in range(size_of_df):
    bootstrapped_indices.append(random.choice(indices))

  # convert to np array for simplicity:
  bootstrapped_indices = np.array(bootstrapped_indices)
  print(bootstrapped_indices) # proof that I am bootstrapping

  # invoke the method from part b:
  coefficients.append(partB(df, bootstrapped_indices) )

[9829 7654 4666 ... 8121 5436 9830]
[4604 9073 2427 ... 4114 2160 1823]
[9258 8728 6831 ... 7786 5098 3489]
[ 906 6178 1748 ... 4508 1721 9984]
[4771 2605 9143 ... 6956 7667 6425]
[ 380   61 8456 ... 3727 9331 2143]
[4140 7974 2153 ... 3634 5916 5204]
[6350 1404 7123 ... 2815 7365 8468]
[4245  235 3459 ... 6696  574 2531]
[ 585 6733 2853 ... 1187 5888 9997]
[1135 9997 6541 ... 6783 5890 2568]
[1292 7560 1914 ... 2538 2325  695]
[4548 5074 1982 ... 9611  513 5811]
[4527 5285 9732 ... 8901 1392 3004]
[3574 2362 6331 ... 6106 7427 1081]
[5803  497 6926 ... 4728 7286 3889]
[8366  576 5638 ... 8318 6435 2003]
[1240 8730 5363 ... 2389 3060 6300]
[4529 8776 5616 ... 3105 7081 7299]
[4683 6544  902 ... 6275 9343 2241]
[9174 5540  144 ... 9708 8697 8214]
[5142 3841 1270 ... 4547 3650 6644]
[6606 8559 3032 ... 9108 7462 6758]
[9958 8839 2523 ... 5350 5650 7647]
[3050 6821 9906 ... 9376 9391 5653]
[6001 6845  562 ... 8964 8823 2091]
[6397 1002 2379 ... 2686 4182 2506]
[7700 4774 4541 ... 3545 523

In [145]:
# Display the coefficients I obtained from running part B n times in part C:
np_coefficients = np.array(coefficients)
print(np_coefficients)
print('amount of sets of coeffiecents this array contains', len(np_coefficients), 'samples')

[[ 6.26227102e-03  2.31728900e-05]
 [ 4.30410716e-04 -1.27457481e-04]
 [ 4.28948568e-04 -1.30224630e-04]
 [ 5.56452755e-03  2.15206765e-05]
 [ 4.45317892e-04 -1.26148869e-04]
 [ 3.97926920e-04 -1.24514147e-04]
 [ 5.42334752e-03  2.30553350e-05]
 [ 5.77696899e-03  2.41254505e-05]
 [ 5.24823038e-04 -1.33873842e-04]
 [ 5.23376120e-03  1.80184406e-05]
 [ 5.61710444e-03  1.66719203e-05]
 [ 5.11864975e-04 -1.29198516e-04]
 [ 4.97581543e-04 -1.28832612e-04]
 [ 5.49181562e-03  2.28253723e-05]
 [ 5.61936566e-03  1.76305207e-05]
 [ 4.86547469e-04 -1.27541891e-04]
 [ 5.59615242e-03  2.32803595e-05]
 [ 5.27996759e-04 -1.30937776e-04]
 [ 5.51727872e-03  1.99088517e-05]
 [ 5.04666488e-04 -1.34632238e-04]
 [ 5.44480082e-03  2.55978626e-05]
 [ 5.40909263e-03  2.16558442e-05]
 [ 5.39774085e-03  1.69889662e-05]
 [ 3.41756787e-04 -1.23818243e-04]
 [ 6.21256223e-03  2.34713547e-05]
 [ 3.09239950e-04 -1.26359681e-04]
 [ 5.30091080e-03  2.35472121e-05]
 [ 5.74905512e-03  2.15365610e-05]
 [ 3.52019360e-04 -1

In [147]:
# Find the standard error of these coefficients:
standard_error_of_bootstrapped_coefficients = sem(np_coefficients)
print('standard error of bootstrapped coefficients:', standard_error_of_bootstrapped_coefficients)

standard error of bootstrapped coefficients: [2.60785288e-04 7.49844152e-06]


# Part D
Comment on the estimated standard errors obtained in (a) and using your bootstrap function (obtained in (c).)

The standard errors for income and balance from part a are respectively 4.99e-06 and 0 while the standard errors in part c are 2.60785288e-04 and 7.49844152e-06. The standard errors in part a are indeed lower than in part C. However, both sets of standard errors are very small which shows quality in both models.

